import Head from "next/head";
import styles from "../styles/Home.module.css";
import { CreateUser } from "../components/src/components/registerPage/CreateUser";
import { HomeDashboard } from "../components/src/components/homeDashboard/HomeDashboard";
import { HomePage } from "../components/src/components/homePage/HomePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <main>
        <HomePage />
      </main>
    </>
  );
}
